const driverData = [
  {
    id: 0,
    driver: 'Lewis Hamilton',
    country: 'United Kingdom',
    team: 'Mercedes-AMG',
    coeff: 1,
  },
  {
    id: 1,
    driver: 'Valtteri Bottas',
    country: 'Finland',
    team: 'Mercedes-AMG',
    coeff: 1.002,
  },
  {
    id: 2,
    driver: 'Max Verstappen',
    country: 'Netherlands',
    team: 'Red Bull Racing Honda',
    coeff: 1.001,
  },
  {
    id: 3,
    driver: 'Sergio Perez',
    country: 'Mexico',
    team: 'Red Bull Racing Honda',
    coeff: 1.003,
  },
  {
    id: 4,
    driver: 'Charles Leclerc',
    country: 'Monaco',
    team: 'Scuderia Ferrari',
    coeff: 1.003,
  },
  {
    id: 5,
    driver: 'Carlos Sainz',
    country: 'Spain',
    team: 'Scuderia Ferrari',
    coeff: 1.005,
  },
  {
    id: 6,
    driver: 'Lando Norris',
    country: 'United Kingdom',
    team: 'McLaren Mercedes',
    coeff: 1.004,
  },
  {
    id: 7,
    driver: 'Daniel Ricciardo',
    country: 'Australia',
    team: 'McLaren Mercedes',
    coeff: 1.005,
  },
  {
    id: 8,
    driver: 'Lance Stroll',
    country: 'Canada',
    team: 'Aston Martin Mercedes',
    coeff: 1.008,
  },
  {
    id: 9,
    driver: 'Sebastian Vettel',
    country: 'Germany',
    team: 'Aston Martin Mercedes',
    coeff: 1.007,
  },
  {
    id: 10,
    driver: 'Esteban Ocon',
    country: 'France',
    team: 'Alpine Renault',
    coeff: 1.006,
  },
  {
    id: 11,
    driver: 'Fernando Alonso',
    country: 'Spain',
    team: 'Alpine Renault',
    coeff: 1.006,
  },
  {
    id: 12,
    driver: 'Pierre Gasly',
    country: 'France',
    team: 'Alpha Tauri Honda',
    coeff: 1.005,
  },
  {
    id: 13,
    driver: 'Yuki Tsunoda',
    country: 'Japan',
    team: 'Alpha Tauri Honda',
    coeff: 1.007,
  },
  {
    id: 14,
    driver: 'Kimi Raikkonen',
    country: 'Finland',
    team: 'Alfa Romeo Ferrari',
    coeff: 1.009,
  },
  {
    id: 15,
    driver: 'Antonio Giovinazzi',
    country: 'Italy',
    team: 'Alfa Romeo Ferrari',
    coeff: 1.009,
  },
  {
    id: 16,
    driver: 'George Russell',
    country: 'United Kingdom',
    team: 'Williams Mercedes',
    coeff: 1.01,
  },
  {
    id: 17,
    driver: 'Nicholas Latifi',
    country: 'Canada',
    team: 'Williams Mercedes',
    coeff: 1.012,
  },
  {
    id: 18,
    driver: 'Mick Schumacher',
    country: 'Germany',
    team: 'Haas Ferrari',
    coeff: 1.015,
  },
  {
    id: 19,
    driver: 'Nikita Mazepin',
    country: 'Russia',
    team: 'Haas Ferrari',
    coeff: 1.02,
  },
];

export default driverData;
